language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - python3 -m venv venv && . venv/bin/activate && pip install -r REQUIREMENTS.txt
# command to run tests
script:
  - . venv/bin/activate && pytest -v --cov=calculator
