language: python
python:
  - "3.6"
  - "3.7"
  - "3.9"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r REQUIREMENTS.txt --use-mirrors
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
  - pytest -v --cov=tests
  - cd -
script:
  - pytest --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
